# Generated by Django 3.1.4 on 2020-12-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0002_auto_20201209_0859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='contact_number',
            new_name='phone',
        ),
    ]
