# Generated by Django 3.1.4 on 2020-12-10 00:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0003_auto_20201209_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='tag',
            new_name='category',
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
        migrations.CreateModel(
            name='Jobber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, max_length=3000)),
                ('interest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobber.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_applied', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_closed', models.BooleanField(default=False)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobber.job')),
            ],
        ),
    ]
