# Generated by Django 3.1.4 on 2020-12-10 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0004_auto_20201210_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='estimate_pay',
            new_name='pay',
        ),
    ]
